#项目相关路径
fast:
  profile: ./file

#spring配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fast?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  #配置默认的用户名和密码
  security:
    user:
      name: admin
      password: 123456

#环境配置
server:
  port: 8080
  servlet:
    context-path: /
#日志配置
logging:
  level:
    #debug级别适合开发阶段 生产阶段info warn
    com.fast: debug
    #spring框架的日志级别  warn只输出警告和错误信息 减少控制台输出
    org.springframework: warn

#mybatis配置
mybatis:
  #告诉mybatis去哪找实体类映射
  type-aliases-package: com.fast.**.domain
  #配置扫描
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    #日志
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

token:
  #请求头的字段名： 前端携带此字段
  header: Authorization
  #令牌密钥 用于加密解密token
  secret: ${JWT_SECRET}
  #令牌有效期（M）
  expireTime: 300